/**
 * R-ARCH first-phase boundary proof.
 *
 * The playtest milestone signal table is now a pure system, not another large
 * switchboard embedded in Game.ts.
 */
import { readFileSync } from 'node:fs'
import { test, expect } from '@playwright/test'

const gameSource = readFileSync(new URL('../src/game/Game.ts', import.meta.url), 'utf8')
const assetLoaderSource = readFileSync(new URL('../src/game/AssetLoader.ts', import.meta.url), 'utf8')
const signalSource = readFileSync(new URL('../src/game/systems/MilestoneSignalSystem.ts', import.meta.url), 'utf8')
const unitPresentationSource = readFileSync(new URL('../src/game/systems/UnitPresentationSystem.ts', import.meta.url), 'utf8')
const visualAudioSource = readFileSync(new URL('../src/game/systems/VisualAudioIdentitySystem.ts', import.meta.url), 'utf8')
const battlefieldPerceptionSource = readFileSync(new URL('../src/game/systems/BattlefieldPerceptionSystem.ts', import.meta.url), 'utf8')
const presentationAssetReadinessSource = readFileSync(new URL('../src/game/systems/PresentationAssetReadinessSystem.ts', import.meta.url), 'utf8')
const heroAbilityPresentationSource = readFileSync(new URL('../src/game/systems/HeroAbilityPresentationSystem.ts', import.meta.url), 'utf8')
const resurrectionReadabilitySource = readFileSync(new URL('../src/game/systems/ResurrectionReadabilitySystem.ts', import.meta.url), 'utf8')
const heroMilestoneSource = readFileSync(new URL('../src/game/systems/HeroMilestoneSystem.ts', import.meta.url), 'utf8')
const resultPresentationSource = readFileSync(new URL('../src/game/systems/ResultPresentationSystem.ts', import.meta.url), 'utf8')
const feedbackEffectsSource = readFileSync(new URL('../src/game/FeedbackEffects.ts', import.meta.url), 'utf8')
const humanRouteSource = readFileSync(new URL('../src/game/systems/HumanRouteSystem.ts', import.meta.url), 'utf8')
const humanCombatProfileSource = readFileSync(new URL('../src/game/systems/HumanCombatProfileSystem.ts', import.meta.url), 'utf8')
const humanUpgradeImpactSource = readFileSync(new URL('../src/game/systems/HumanUpgradeImpactSystem.ts', import.meta.url), 'utf8')
const audioCueSource = readFileSync(new URL('../src/game/systems/AudioCueSystem.ts', import.meta.url), 'utf8')
const playtestReadinessSource = readFileSync(new URL('../src/game/systems/PlaytestReadinessSystem.ts', import.meta.url), 'utf8')
const war3GapSource = readFileSync(new URL('../src/game/systems/War3GapSystem.ts', import.meta.url), 'utf8')
const commandRouteMetadataSource = readFileSync(new URL('../src/game/ui/HumanCommandRouteMetadata.ts', import.meta.url), 'utf8')
const commandCardPresenterSource = readFileSync(new URL('../src/game/ui/CommandCardPresenter.ts', import.meta.url), 'utf8')
const commandButtonStatusSource = readFileSync(new URL('../src/game/ui/CommandButtonStatus.ts', import.meta.url), 'utf8')
const commandIconDrawerSource = readFileSync(new URL('../src/game/ui/CommandIconDrawers.ts', import.meta.url), 'utf8')
const selectionHudPresenterSource = readFileSync(new URL('../src/game/ui/SelectionHudPresenter.ts', import.meta.url), 'utf8')
const buildingCommandButtonSource = readFileSync(new URL('../src/game/ui/BuildingCommandButtonBuilders.ts', import.meta.url), 'utf8')
const unitCommandButtonSource = readFileSync(new URL('../src/game/ui/UnitCommandButtonBuilders.ts', import.meta.url), 'utf8')
const heroCommandButtonSource = readFileSync(new URL('../src/game/ui/HeroCommandButtonBuilders.ts', import.meta.url), 'utf8')
const inventoryCommandButtonSource = readFileSync(new URL('../src/game/ui/InventoryCommandButtonBuilders.ts', import.meta.url), 'utf8')

test.describe('R-ARCH milestone signal boundary', () => {
  test('Game delegates playtest milestone signal composition to MilestoneSignalSystem', () => {
    const start = gameSource.indexOf('private getPlaytestMilestoneSignals')
    const end = gameSource.indexOf('renderPlaytestReadinessPanel', start)
    const methodSource = gameSource.slice(start, end)

    expect(start).toBeGreaterThanOrEqual(0)
    expect(end).toBeGreaterThan(start)
    expect(gameSource).toContain("import { buildPlaytestMilestoneSignals } from './systems/MilestoneSignalSystem'")
    expect(gameSource).toContain('private getRuntimeMilestoneSnapshots')
    expect(methodSource).toContain('return buildPlaytestMilestoneSignals(this.getRuntimeMilestoneSnapshots())')
    expect(methodSource).not.toContain("label: 'Human 路线'")
    expect(methodSource).not.toContain("label: '视听反馈'")
  })

  test('MilestoneSignalSystem owns R7/R14/R15-facing summary language', () => {
    expect(signalSource).toContain('export function buildPlaytestMilestoneSignals')
    expect(signalSource).toContain("key: 'R7'")
    expect(signalSource).toContain("key: 'R14'")
    expect(signalSource).toContain('r7.tier.currentTierLabel')
    expect(signalSource).toContain('r7.rhythm.phaseLabel')
    expect(signalSource).toContain('r7.rhythm.roleCoverageCount')
    expect(signalSource).toContain('r14.presentationCheckCount')
    expect(signalSource).toContain('r14.unitPresentation.clipBackedUnitCount')
    expect(signalSource).toContain('r14.resultPresentation.cardCount')
  })

  test('UnitPresentationSystem owns unit animation state instead of expanding Game render logic', () => {
    expect(unitPresentationSource).toContain('export class UnitPresentationSystem')
    expect(unitPresentationSource).toContain('export interface UnitPresentationSnapshot')
    expect(unitPresentationSource).toContain('function classifyUnit')
    expect(unitPresentationSource).toContain('function applyPose')
    expect(unitPresentationSource).toContain('selectClipForState')
    expect(unitPresentationSource).toContain('THREE.AnimationMixer')
    expect(unitPresentationSource).toContain('THREE.LoopOnce')
    expect(gameSource).toContain("import { UnitPresentationSystem } from './systems/UnitPresentationSystem'")
    expect(gameSource).toContain('this.unitPresentation.update(this.units, dt, this.gameTime)')
    expect(gameSource).toContain('getUnitPresentationSnapshot()')
    expect(visualAudioSource).toContain("import type { UnitPresentationSnapshot } from './UnitPresentationSystem'")
    expect(visualAudioSource).toContain("key: 'unit-motion-language'")
    expect(visualAudioSource).toContain("key: 'animation-source-contract'")
    expect(assetLoaderSource).toContain('assetAnimations')
    expect(assetLoaderSource).toContain('getAssetAnimationClipNames')
  })

  test('BattlefieldPerceptionSystem owns R14 player-facing feedback coverage', () => {
    expect(battlefieldPerceptionSource).toContain('export function buildBattlefieldPerceptionSnapshot')
    expect(battlefieldPerceptionSource).toContain("key: 'command-confirmation'")
    expect(battlefieldPerceptionSource).toContain("key: 'combat-impact'")
    expect(battlefieldPerceptionSource).toContain("key: 'death-readability'")
    expect(battlefieldPerceptionSource).toContain("key: 'audio-palette'")
    expect(visualAudioSource).toContain("import {")
    expect(visualAudioSource).toContain("} from './BattlefieldPerceptionSystem'")
    expect(visualAudioSource).toContain('perceptionCheckCount')
    expect(visualAudioSource).toContain('perception.completedCount')
    expect(gameSource).toContain('deadRecordCount: this.deadUnitRecords.length')
    expect(gameSource).toContain("this.playAudioCue('combat', '命中')")
    expect(gameSource).toContain("this.playAudioCue('death',")
    expect(audioCueSource).toContain("| 'combat'")
    expect(audioCueSource).toContain("| 'death'")
    expect(audioCueSource).toContain('assets/audio/cues/command.wav')
    expect(audioCueSource).toContain('assets/audio/cues/result.wav')
    expect(audioCueSource).toContain('export function getAudioCueAssetPath')
    expect(audioCueSource).toContain('playAssetCue')
  })

  test('PresentationAssetReadinessSystem owns real clip and audio asset gate', () => {
    expect(presentationAssetReadinessSource).toContain('export function buildPresentationAssetReadinessSnapshot')
    expect(presentationAssetReadinessSource).toContain("worker: ['idle', 'walk', 'work', 'death']")
    expect(presentationAssetReadinessSource).toContain("'combat'")
    expect(presentationAssetReadinessSource).toContain("'procedural-oscillator'")
    expect(presentationAssetReadinessSource).toContain('contractCoverageComplete')
    expect(presentationAssetReadinessSource).toContain('finalAssetApproved')
    expect(presentationAssetReadinessSource).toContain('finalArtReady')
    expect(visualAudioSource).toContain("} from './PresentationAssetReadinessSystem'")
    expect(visualAudioSource).toContain('assetReadinessCheckCount')
    expect(visualAudioSource).toContain('assetReadiness.completedCount')
    expect(gameSource).toContain('getAssetAnimationClipNames')
    expect(gameSource).toContain('getAssetAnimationClipNames,')
    expect(gameSource).toContain('getAudioCueAssetPath')
    expect(visualAudioSource).toContain('getAudioCueAssetPath?:')
    expect(signalSource).toContain('r14.assetReadiness.realClipStateCount')
    expect(war3GapSource).toContain('r14.assetReadiness.finalArtReady')
  })

  test('HeroAbilityPresentationSystem owns hero targeting preview semantics outside Game', () => {
    expect(heroAbilityPresentationSource).toContain('export function buildHeroAbilityPresentationSnapshot')
    expect(heroAbilityPresentationSource).toContain("key: 'range-preview-contract'")
    expect(heroAbilityPresentationSource).toContain("key: 'target-cursor-contract'")
    expect(heroAbilityPresentationSource).toContain("key: 'area-preview-contract'")
    expect(heroAbilityPresentationSource).toContain("key: 'legality-state-contract'")
    expect(heroAbilityPresentationSource).toContain("key: 'active-target-legality-contract'")
    expect(heroAbilityPresentationSource).toContain('ActiveHeroAbilityTargetEvaluation')
    expect(heroAbilityPresentationSource).toContain('activeTargetMarkerCount')
    expect(gameSource).toContain("} from './systems/HeroAbilityPresentationSystem'")
    expect(gameSource).toContain('getActiveHeroTargetModeSnapshot()')
    expect(gameSource).toContain('getActiveHeroTargetEvaluation()')
    expect(gameSource).toContain('updateHeroAbilityPreviews()')
    expect(gameSource).toContain('this.feedback.updateAbilityPreviews')
    expect(visualAudioSource).toContain("} from './HeroAbilityPresentationSystem'")
    expect(visualAudioSource).toContain("key: 'ability-targeting-language'")
    expect(visualAudioSource).toContain('abilityTargetMarkerCount')
  })

  test('ResurrectionReadabilitySystem owns Paladin corpse and resurrection range readability outside Game', () => {
    expect(resurrectionReadabilitySource).toContain('export function buildResurrectionReadabilitySnapshot')
    expect(resurrectionReadabilitySource).toContain("key: 'corpse-record-surface'")
    expect(resurrectionReadabilitySource).toContain("key: 'resurrection-radius-surface'")
    expect(resurrectionReadabilitySource).toContain("key: 'eligible-corpse-surface'")
    expect(resurrectionReadabilitySource).toContain('visibleEligibleCorpseMarkerCount')
    expect(heroMilestoneSource).toContain("} from './ResurrectionReadabilitySystem'")
    expect(heroMilestoneSource).toContain('resurrectionReadability: ResurrectionReadabilitySnapshot')
    expect(gameSource).toContain('updateResurrectionReadability')
    expect(gameSource).toContain('resurrectionReadability: hero.resurrectionReadability')
    expect(visualAudioSource).toContain("from './ResurrectionReadabilitySystem'")
    expect(visualAudioSource).toContain("key: 'resurrection-corpse-language'")
    expect(visualAudioSource).toContain('resurrectionRadiusRingCount')
  })

  test('ResultPresentationSystem and FeedbackEffects own R14 spell/result presentation surfaces', () => {
    expect(resultPresentationSource).toContain('export function buildResultPresentationSnapshot')
    expect(resultPresentationSource).toContain("key: 'result-card-layer'")
    expect(resultPresentationSource).toContain("key: 'objective-recap-layer'")
    expect(resultPresentationSource).toContain("key: 'flow-recap-layer'")
    expect(resultPresentationSource).toContain("key: 'pressure-recap-layer'")
    expect(resultPresentationSource).toContain("key: 'combat-reason-layer'")
    expect(resultPresentationSource).toContain("key: 'tech-impact'")
    expect(resultPresentationSource).toContain("from './HumanUpgradeImpactSystem'")
    expect(gameSource).toContain("} from './systems/ResultPresentationSystem'")
    expect(gameSource).toContain('getResultPresentationSnapshot()')
    expect(gameSource).toContain('renderResultPresentation')
    expect(visualAudioSource).toContain("from './ResultPresentationSystem'")
    expect(visualAudioSource).toContain("key: 'result-visual-recap'")
    expect(feedbackEffectsSource).toContain('spawnAbilityEffectBurst')
    expect(feedbackEffectsSource).toContain('totalAbilityEffectBursts')
    expect(visualAudioSource).toContain("key: 'ability-effect-language'")
    expect(playtestReadinessSource).toContain("key: 'result-recap-surface'")
    expect(war3GapSource).toContain('r14.resultPresentation.cardCount')
  })

  test('HumanRouteSystem owns R7 tech rhythm and tactical role language', () => {
    expect(humanRouteSource).toContain('export interface HumanRouteRhythmSummary')
    expect(humanRouteSource).toContain('roleCoverageCount')
    expect(humanRouteSource).toContain('recommendedFocus')
    expect(humanRouteSource).toContain('nextPowerSpike')
    expect(humanRouteSource).toContain('T2 支援/攻城在线')
    expect(humanRouteSource).toContain("from './HumanCombatProfileSystem'")
    expect(humanRouteSource).toContain('combat: HumanCombatProfileSnapshot')
    expect(humanRouteSource).toContain("from './HumanUpgradeImpactSystem'")
    expect(humanRouteSource).toContain('upgradeImpact: HumanUpgradeImpactSnapshot')
    expect(humanCombatProfileSource).toContain('export function buildHumanCombatProfileSnapshot')
    expect(humanCombatProfileSource).toContain('counterAdvantageCount')
    expect(humanCombatProfileSource).toContain('recommendedMix')
    expect(humanUpgradeImpactSource).toContain('export function buildHumanUpgradeImpactSnapshot')
    expect(humanUpgradeImpactSource).toContain('battleReason')
    expect(humanUpgradeImpactSource).toContain('nextUpgradeHint')
    expect(gameSource).toContain('snapshot.rhythm.phaseLabel')
    expect(gameSource).toContain('human-route-unlock-role')
    expect(gameSource).toContain('human-route-unlock-counter')
    expect(gameSource).toContain('snapshot.combat.compositionCoverageCount')
    expect(gameSource).toContain('snapshot.upgradeImpact.completedResearchCount')
    expect(signalSource).toContain('r7.combat.counterAdvantageCount')
    expect(signalSource).toContain('r7.upgradeImpact.completedResearchCount')
    expect(war3GapSource).toContain('r7.rhythm.roleCoverageCount')
    expect(war3GapSource).toContain('r7.rhythm.recommendedFocus')
    expect(war3GapSource).toContain('r7.combat.compositionCoverageCount')
    expect(war3GapSource).toContain('r7.upgradeImpact.completedResearchCount')
  })

  test('HumanCommandRouteMetadata owns R7/R4 command-card route language outside Game', () => {
    expect(commandRouteMetadataSource).toContain('export function getBuildingCommandMetadata')
    expect(commandRouteMetadataSource).toContain('export function getTrainingCommandMetadata')
    expect(commandRouteMetadataSource).toContain('export function getResearchCommandMetadata')
    expect(commandRouteMetadataSource).toContain('human-t2-caster-line')
    expect(commandRouteMetadataSource).toContain('human-t2-workshop-siege')
    expect(commandRouteMetadataSource).toContain('human-t3-knight-frontline')
    expect(commandRouteMetadataSource).toContain('human-t3-castle-transition')
    expect(commandCardPresenterSource).toContain('export type CommandCardRouteMeta')
    expect(commandCardPresenterSource).toContain('btn.dataset.routeKey')
    expect(commandCardPresenterSource).toContain("this.createSpan('btn-route'")
    expect(buildingCommandButtonSource).toContain("from './HumanCommandRouteMetadata'")
    expect(unitCommandButtonSource).toContain("from './HumanCommandRouteMetadata'")
    expect(gameSource).not.toContain('human-t2-caster-line')
    expect(gameSource).not.toContain('human-t2-workshop-siege')
  })

  test('CommandCardPresenter owns executable hotkeys and Game only delegates keyboard entry', () => {
    expect(commandCardPresenterSource).toContain('export type CommandCardHotkeyResult')
    expect(commandCardPresenterSource).toContain('triggerHotkey(key: string)')
    expect(commandCardPresenterSource).toContain("this.pulseButton(button, 'cmd-hotkey-fired')")
    expect(commandCardPresenterSource).toContain("this.pulseButton(button, 'cmd-hotkey-blocked')")
    expect(commandCardPresenterSource).toContain('cmd-card-hotkey-fired')
    expect(commandCardPresenterSource).toContain('cmd-card-hotkey-blocked')
    expect(commandCardPresenterSource).toContain('btn.dataset.hotkey')
    expect(gameSource).toContain('private triggerCommandCardHotkey(e: KeyboardEvent)')
    expect(gameSource).toContain('this.commandCardPresenter.triggerHotkey(e.key)')
    expect(gameSource).toContain('this.flashCommandCardHint')
    expect(gameSource).toContain('命令卡不可用')
    expect(gameSource).toContain('若当前命令卡有 P 热键，上面的命令卡路径优先')
  })

  test('Command-card icon identity is a UI contract outside Game', () => {
    expect(commandCardPresenterSource).toContain('iconKey?: string')
    expect(commandCardPresenterSource).toContain('btn.dataset.iconKey')
    expect(commandCardPresenterSource).toContain('btn.dataset.commandState')
    expect(commandCardPresenterSource).toContain('btn.dataset.meterRemaining')
    expect(commandCardPresenterSource).toContain('btn-resource-debt')
    expect(commandCardPresenterSource).toContain('btn-state-badge')
    expect(commandCardPresenterSource).toContain('btn-icon-canvas')
    expect(commandCardPresenterSource).toContain('drawCommandIcon(canvas, iconKey)')
    expect(commandButtonStatusSource).toContain('export function makeCooldownMeter')
    expect(commandButtonStatusSource).toContain('export function makeManaRequirement')
    expect(commandButtonStatusSource).toContain("kind: 'mana'")
    expect(commandIconDrawerSource).toContain('export function drawCommandIcon')
    expect(commandIconDrawerSource).toContain('export function describeCommandIcon')
    expect(commandIconDrawerSource).toContain("drawMiniPortrait(canvas, key, 0)")
    expect(commandIconDrawerSource).toContain("kind === 'item'")
    expect(commandIconDrawerSource).toContain("kind === 'research'")
    expect(commandIconDrawerSource).toContain("kind === 'ability'")
    expect(buildingCommandButtonSource).toContain('iconKey: `unit:${unitKey}`')
    expect(buildingCommandButtonSource).toContain('iconKey: `research:${researchKey}`')
    expect(buildingCommandButtonSource).toContain('iconKey: `item:${itemKey}`')
    expect(unitCommandButtonSource).toContain('iconKey: `building:${buildingKey}`')
    expect(unitCommandButtonSource).toContain("iconKey: 'command:attack_move'")
    expect(heroCommandButtonSource).toContain('iconKey: `ability:${abilityKey}`')
    expect(inventoryCommandButtonSource).toContain('iconKey: `item:${itemType}`')
    expect(selectionHudPresenterSource).toContain('appendHeroInventorySlots')
    expect(selectionHudPresenterSource).toContain('selection-inventory-slot')
    expect(selectionHudPresenterSource).toContain("drawCommandIcon(canvas, iconKey)")
    expect(gameSource).not.toContain('btn-icon-canvas')
    expect(gameSource).not.toContain('drawCommandIcon')
  })

  test('War3GapSystem owns full-product gap radar instead of hiding it in R15 copy', () => {
    expect(war3GapSource).toContain('export function buildWar3GapSnapshot')
    expect(war3GapSource).toContain("key: 'front-door-shell'")
    expect(war3GapSource).toContain("key: 'visual-audio-identity'")
    expect(war3GapSource).toContain("key: 'architecture-maintainability'")
    expect(war3GapSource).toContain("key: 'ai-opponent-depth'")
    expect(gameSource).toContain("import { buildWar3GapSnapshot } from './systems/War3GapSystem'")
    expect(gameSource).toContain('getWar3GapSnapshot()')
    expect(gameSource).toContain('war3Gap: this.getWar3GapSnapshot()')
    expect(playtestReadinessSource).toContain('War3 gap radar:')
    expect(playtestReadinessSource).toContain("key: 'war3-gap-radar'")
  })
})
